function doe$1(e){let t=0,n={function:t=>t(e),number:o,object:r,string:d};return c([...arguments].slice(1)),e;function o(e){t=e;}function r(n){function o(){n.map(c);}n instanceof Array?o():n instanceof Node?e[t?"removeChild":"appendChild"](n):"length"in n||n[Symbol.iterator]?(n=Array.from(n),o()):t?Object.entries(n).map((([t,n])=>e.setAttribute(t,n))):Object.assign(e,n);}function d(t){e.appendChild(document.createTextNode(t));}function c(e){for(let t;t=n[typeof e];e=t(e));}}let method$1={html(){return doe$1(document.documentElement,...arguments)},head(){return doe$1(document.head,...arguments)},body(){return doe$1(document.body,...arguments)}};var main$1 = new Proxy(doe$1,{get:(e,t)=>method$1[t]||function(){return doe$1(document.createElement(t),...arguments)}});

function doe(e){let t=0,n={function:t=>t(e),number:a,object:o,string:i};return r([...arguments].slice(1)),e;function a(e){t=e;}function o(n){function a(){n.map(r);}n instanceof Array?a():n instanceof Node?e[t?"removeChild":"appendChild"](n):"length"in n||n[Symbol.iterator]?(n=Array.from(n),a()):t?Object.entries(n).map((([t,n])=>e.setAttribute(t,n))):Object.assign(e,n);}function i(t){e.appendChild(document.createTextNode(t));}function r(e){for(let t;t=n[typeof e];e=t(e));}}let method={html(){return doe(document.documentElement,...arguments)},head(){return doe(document.head,...arguments)},body(){return doe(document.body,...arguments)}};var main=new Proxy(doe,{get:(e,t)=>method[t]||function(){return doe(document.createElement(t),...arguments)}});let skip=60;function QrCodeScanner(e){this._worker=new Worker(e),this._worker.onmessage=e=>this.onRead(e.data),this._canvas=main.canvas(),this._context=this._canvas.getContext("2d"),this.node=main.video({onloadedmetadata:e=>{this._canvas.width=this.node.videoWidth,this._canvas.height=this.node.videoHeight;}}),this._load=(async()=>{this.node.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});})();}QrCodeScanner.prototype.start=async function(){await this._load,await this.node.play();let e=0,t=()=>{this._frame=requestAnimationFrame(t),this._context.drawImage(this.node,0,0),e++%skip==0&&this._worker.postMessage(this._context.getImageData(0,0,this._canvas.width,this._canvas.height));};this._frame=requestAnimationFrame(t);},QrCodeScanner.prototype.end=function(){cancelAnimationFrame(this._frame);};

let qrCodeScanner=new QrCodeScanner('qrWorker.static.mjs')
;(async()=>{
    main$1.body(qrCodeScanner.node);
    await qrCodeScanner.start();
    qrCodeScanner.onRead=console.log;
})();
